//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaOtomasyon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BankaDBEntities : DbContext
    {
        public BankaDBEntities()
            : base("name=BankaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblMusteri> tblMusteri { get; set; }
        public DbSet<tblMusteriHesap> tblMusteriHesap { get; set; }
        public DbSet<tblVirman> tblVirman { get; set; }
        public DbSet<tblHavale> tblHavale { get; set; }
    
        public virtual int ParaCek(Nullable<decimal> hesapBakiye, Nullable<int> hesapEkNumarasi, Nullable<int> musteriId)
        {
            var hesapBakiyeParameter = hesapBakiye.HasValue ?
                new ObjectParameter("hesapBakiye", hesapBakiye) :
                new ObjectParameter("hesapBakiye", typeof(decimal));
    
            var hesapEkNumarasiParameter = hesapEkNumarasi.HasValue ?
                new ObjectParameter("hesapEkNumarasi", hesapEkNumarasi) :
                new ObjectParameter("hesapEkNumarasi", typeof(int));
    
            var musteriIdParameter = musteriId.HasValue ?
                new ObjectParameter("musteriId", musteriId) :
                new ObjectParameter("musteriId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ParaCek", hesapBakiyeParameter, hesapEkNumarasiParameter, musteriIdParameter);
        }
    
        public virtual int ParaYatir(Nullable<decimal> hesapBakiye, Nullable<int> hesapEkNumarasi, Nullable<int> musteriId)
        {
            var hesapBakiyeParameter = hesapBakiye.HasValue ?
                new ObjectParameter("hesapBakiye", hesapBakiye) :
                new ObjectParameter("hesapBakiye", typeof(decimal));
    
            var hesapEkNumarasiParameter = hesapEkNumarasi.HasValue ?
                new ObjectParameter("hesapEkNumarasi", hesapEkNumarasi) :
                new ObjectParameter("hesapEkNumarasi", typeof(int));
    
            var musteriIdParameter = musteriId.HasValue ?
                new ObjectParameter("musteriId", musteriId) :
                new ObjectParameter("musteriId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ParaYatir", hesapBakiyeParameter, hesapEkNumarasiParameter, musteriIdParameter);
        }
    
        public virtual ObjectResult<Doldur_Result> Doldur(Nullable<int> hesapekno, Nullable<int> hesapnumarasi)
        {
            var hesapeknoParameter = hesapekno.HasValue ?
                new ObjectParameter("hesapekno", hesapekno) :
                new ObjectParameter("hesapekno", typeof(int));
    
            var hesapnumarasiParameter = hesapnumarasi.HasValue ?
                new ObjectParameter("hesapnumarasi", hesapnumarasi) :
                new ObjectParameter("hesapnumarasi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Doldur_Result>("Doldur", hesapeknoParameter, hesapnumarasiParameter);
        }
    
        public virtual int Virman(Nullable<int> aliciEkNo, Nullable<int> gonderenEkNo, Nullable<int> bakiye, Nullable<int> hesapNo)
        {
            var aliciEkNoParameter = aliciEkNo.HasValue ?
                new ObjectParameter("aliciEkNo", aliciEkNo) :
                new ObjectParameter("aliciEkNo", typeof(int));
    
            var gonderenEkNoParameter = gonderenEkNo.HasValue ?
                new ObjectParameter("gonderenEkNo", gonderenEkNo) :
                new ObjectParameter("gonderenEkNo", typeof(int));
    
            var bakiyeParameter = bakiye.HasValue ?
                new ObjectParameter("bakiye", bakiye) :
                new ObjectParameter("bakiye", typeof(int));
    
            var hesapNoParameter = hesapNo.HasValue ?
                new ObjectParameter("hesapNo", hesapNo) :
                new ObjectParameter("hesapNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Virman", aliciEkNoParameter, gonderenEkNoParameter, bakiyeParameter, hesapNoParameter);
        }
    
        public virtual int VirmanKaydet(Nullable<int> aliciEkNo, Nullable<int> gonderenEkNo, Nullable<int> bakiye, Nullable<int> hesapNo, Nullable<System.DateTime> tarih)
        {
            var aliciEkNoParameter = aliciEkNo.HasValue ?
                new ObjectParameter("aliciEkNo", aliciEkNo) :
                new ObjectParameter("aliciEkNo", typeof(int));
    
            var gonderenEkNoParameter = gonderenEkNo.HasValue ?
                new ObjectParameter("gonderenEkNo", gonderenEkNo) :
                new ObjectParameter("gonderenEkNo", typeof(int));
    
            var bakiyeParameter = bakiye.HasValue ?
                new ObjectParameter("bakiye", bakiye) :
                new ObjectParameter("bakiye", typeof(int));
    
            var hesapNoParameter = hesapNo.HasValue ?
                new ObjectParameter("hesapNo", hesapNo) :
                new ObjectParameter("hesapNo", typeof(int));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("tarih", tarih) :
                new ObjectParameter("tarih", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VirmanKaydet", aliciEkNoParameter, gonderenEkNoParameter, bakiyeParameter, hesapNoParameter, tarihParameter);
        }
    
        public virtual int Havale(Nullable<int> gonderenhesapno, Nullable<decimal> bakiye, Nullable<int> alicihesapno, Nullable<int> gonderenEkNo, Nullable<int> aliciEkNo)
        {
            var gonderenhesapnoParameter = gonderenhesapno.HasValue ?
                new ObjectParameter("gonderenhesapno", gonderenhesapno) :
                new ObjectParameter("gonderenhesapno", typeof(int));
    
            var bakiyeParameter = bakiye.HasValue ?
                new ObjectParameter("bakiye", bakiye) :
                new ObjectParameter("bakiye", typeof(decimal));
    
            var alicihesapnoParameter = alicihesapno.HasValue ?
                new ObjectParameter("alicihesapno", alicihesapno) :
                new ObjectParameter("alicihesapno", typeof(int));
    
            var gonderenEkNoParameter = gonderenEkNo.HasValue ?
                new ObjectParameter("gonderenEkNo", gonderenEkNo) :
                new ObjectParameter("gonderenEkNo", typeof(int));
    
            var aliciEkNoParameter = aliciEkNo.HasValue ?
                new ObjectParameter("aliciEkNo", aliciEkNo) :
                new ObjectParameter("aliciEkNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Havale", gonderenhesapnoParameter, bakiyeParameter, alicihesapnoParameter, gonderenEkNoParameter, aliciEkNoParameter);
        }
    
        public virtual int HavaleKaydet(Nullable<int> aliciEkNo, Nullable<int> gonderenEkNo, Nullable<decimal> bakiye, Nullable<int> aliciHesapNo, Nullable<int> gonderenHesapNo, Nullable<System.DateTime> tarih)
        {
            var aliciEkNoParameter = aliciEkNo.HasValue ?
                new ObjectParameter("aliciEkNo", aliciEkNo) :
                new ObjectParameter("aliciEkNo", typeof(int));
    
            var gonderenEkNoParameter = gonderenEkNo.HasValue ?
                new ObjectParameter("gonderenEkNo", gonderenEkNo) :
                new ObjectParameter("gonderenEkNo", typeof(int));
    
            var bakiyeParameter = bakiye.HasValue ?
                new ObjectParameter("bakiye", bakiye) :
                new ObjectParameter("bakiye", typeof(decimal));
    
            var aliciHesapNoParameter = aliciHesapNo.HasValue ?
                new ObjectParameter("aliciHesapNo", aliciHesapNo) :
                new ObjectParameter("aliciHesapNo", typeof(int));
    
            var gonderenHesapNoParameter = gonderenHesapNo.HasValue ?
                new ObjectParameter("gonderenHesapNo", gonderenHesapNo) :
                new ObjectParameter("gonderenHesapNo", typeof(int));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("tarih", tarih) :
                new ObjectParameter("tarih", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HavaleKaydet", aliciEkNoParameter, gonderenEkNoParameter, bakiyeParameter, aliciHesapNoParameter, gonderenHesapNoParameter, tarihParameter);
        }
    
        public virtual int hgsSatis(Nullable<int> ekNo, Nullable<int> musteriNo)
        {
            var ekNoParameter = ekNo.HasValue ?
                new ObjectParameter("ekNo", ekNo) :
                new ObjectParameter("ekNo", typeof(int));
    
            var musteriNoParameter = musteriNo.HasValue ?
                new ObjectParameter("musteriNo", musteriNo) :
                new ObjectParameter("musteriNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("hgsSatis", ekNoParameter, musteriNoParameter);
        }
    
        public virtual int hgsBakiyeYukle(Nullable<decimal> bakiye, Nullable<int> ekno, Nullable<int> musteriNo)
        {
            var bakiyeParameter = bakiye.HasValue ?
                new ObjectParameter("bakiye", bakiye) :
                new ObjectParameter("bakiye", typeof(decimal));
    
            var eknoParameter = ekno.HasValue ?
                new ObjectParameter("ekno", ekno) :
                new ObjectParameter("ekno", typeof(int));
    
            var musteriNoParameter = musteriNo.HasValue ?
                new ObjectParameter("musteriNo", musteriNo) :
                new ObjectParameter("musteriNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("hgsBakiyeYukle", bakiyeParameter, eknoParameter, musteriNoParameter);
        }
    }
}
