//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaOtomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHavale
    {
        public int havaleId { get; set; }
        public Nullable<decimal> bakiye { get; set; }
        public Nullable<System.DateTime> havaleTarih { get; set; }
        public Nullable<int> havaleAliciHesapNo { get; set; }
        public Nullable<int> havaleGonderenHesapNo { get; set; }
        public Nullable<int> havaleAliciEkNo { get; set; }
        public Nullable<int> havaleGonderenEkNo { get; set; }
    }
}
