//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaOtomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMusteri
    {
        public tblMusteri()
        {
            this.tblMusteriHesap = new HashSet<tblMusteriHesap>();
        }
    
        public int musteriId { get; set; }
        public string musteriAd { get; set; }
        public string musteriSoyAd { get; set; }
        public Nullable<long> musteriTCKN { get; set; }
        public string musteriMail { get; set; }
        public string musteriSifre { get; set; }
        public string musteriTelefon { get; set; }
        public Nullable<int> musteriNumarası { get; set; }
    
        public virtual ICollection<tblMusteriHesap> tblMusteriHesap { get; set; }
    }
}
