//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaOtomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMusteriHesap
    {
        public int hesapId { get; set; }
        public Nullable<int> hesapNumarasi { get; set; }
        public Nullable<decimal> hesapBakiye { get; set; }
        public Nullable<System.DateTime> hesapAcilisTarihi { get; set; }
        public Nullable<System.DateTime> hesapKapanisTarihi { get; set; }
        public Nullable<int> hesapEkNumarasi { get; set; }
        public Nullable<int> musteriId { get; set; }
        public Nullable<bool> hesapAcikMi { get; set; }
    
        public virtual tblMusteri tblMusteri { get; set; }
    }
}
